import Mock from 'mockjs'

let list=[]
export default {
    getStatisticalData:()=>{
        for(let i=0;i<7;i++){
            list.push(
                Mock.mock({
                    异常登记:Mock.Random.float(0,20,0,0),
                    物资申请:Mock.Random.float(0,20,0,0),
                    出入次数:Mock.Random.float(0,40,0,0),
                    志愿人数:Mock.Random.float(0,12,0,0),
                    发布志愿:Mock.Random.float(0,20,0,0),
                })
            )
        }
        return{
            code:20000,
            data:{
                //饼图
                ageData:[
                    {
                        name:'60岁以上',
                        value:2
                    },
                    {
                        name:'40-60岁',
                        value:4
                    },
                    {
                        name:'18-40岁',
                        value:5
                    },
                    {
                        name:'0-18岁',
                        value:1
                    },

                ],
                //柱状图
                serveData:[
                    {
                        data:'周一',
                        new:2,
                        active:11
                    },
                    {
                        data:'周二',
                        new:1,
                        active:10
                    },
                    {
                        data:'周三',
                        new:0,
                        active:8
                    },
                    {
                        data:'周四',
                        new:1,
                        active:7
                    },
                    {
                        data:'周五',
                        new:2,
                        active:9
                    },
                    {
                        data:'周六',
                        new:1,
                        active:12
                    },
                    {
                        data:'周日',
                        new:0,
                        active:10
                    },
                ],
                //折线图
                orderData:{
                    date:['20230413','20230414','20230415','20230416','20230417','20230418','20230419'],
                    data:list
                },
                tableData:[
                    {
                        name:'小明',
                        todayBuy:300,
                        monthBuy:3200,
                    },
                    {
                        name:'小拉姆',
                        todayBuy:300,
                        monthBuy:3200,
                    },
                    {
                        name:'小蓝',
                        todayBuy:300,
                        monthBuy:3200,
                    },
                    {
                        name:'小红',
                        todayBuy:300,
                        monthBuy:3200,
                    },
                    {
                        name:'李华',
                        todayBuy:300,
                        monthBuy:3200,
                    },
                ]
            }
        }
    }
}
